import {test} from "../fixtures/createuserFixture";
import {expect} from "@playwright/test";
import {ConsentPage} from "../pages/ConsentPage";
import { URL } from "../config/constants";
import { USERS } from "../config/constants";
import {automationexercise} from "../pages/AutomationPage";
import { ReachLoginPage } from "../pages/LoginPage";
test("Search for products", async ({page})=>{
    const automationPage = new automationexercise(page);
    const consentPage = new ConsentPage(page);
    const loginPage = new ReachLoginPage(page);
    await automationPage.goto();
    await automationPage.load();
    await consentPage.giveConsent();
    await expect(page).toHaveURL(URL);
    await automationPage.navigateToProducts();
    await expect(page.getByRole('heading', { name: 'All Products' })).toBeVisible();
    const product = page.locator('[class="product-image-wrapper"]');
    const firstProduct = product.first();
    await firstProduct.scrollIntoViewIfNeeded();
    await firstProduct.hover();
    await page.getByText('Add to cart').nth(0).click();
    await page.getByRole('button', { name: 'Continue Shopping' }).click();
    const secondProduct = product.nth(1); 
    await secondProduct.scrollIntoViewIfNeeded();
    await secondProduct.hover()
    await page.getByText('Add to cart').nth(3).click();
    await page.getByRole('button', { name: 'Continue Shopping' }).click();
    await automationPage.navigateToCart();
    await expect(page.getByRole('link', { name: 'Blue Top' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Men Tshirt' })).toBeVisible();
    await loginPage.goto();
    await loginPage.load();
    await consentPage.giveConsent();
    await loginPage.login(USERS.email1,USERS.password);
    await expect(page.getByText(`Logged in as ${USERS.name1}`)).toBeVisible();
    await automationPage.navigateToCart();
    await expect(page.getByRole('link', { name: 'Blue Top' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Men Tshirt' })).toBeVisible();

});